### ISSUE TITLE
plugin breaks getkirby/layouts 

### ISSUE THREAD

**Issue by WebMechanic** [arnoson/kirby-components#1]
Hi,

this plugin breaks https://github.com/getkirby/layouts by also declaring `slots()`

**Comment by arnoson** [comment]
Hi @WebMechanic, thanks for pointing this out. Do you have any suggestions on how to deal with this? I guess either rename `slot` to `beginSlot` (this would also be consistent with the `beginComponent` / `endComponent`) or something else. Or checking if there is currently a component open and if so, treat it as a component slot and otherwise as a layout slot.

**Comment by WebMechanic** [comment]
I believe `beginSlot` would only get you half thru the, 'cos `endslot()` is also already used by Kirby's Layouts. Having both your `endSlot()` and Kirby's `endslot()` is confusing at best and error prone down the line.

Both plugins sounded interesting and also using Vue the "component" concept seems reasonable to give it a try on the server side as well :)
I installed both in one go and the test site broke.

You could probably go with `slotStart` and `slotEnd` and also rename the others to `componentStart` and `componentEnd` so they match - at least the proxy functions in your `helper.php`. 
Then bump the version to `0.1.0` :-)
Side effect: better sorting in IDE.

The rename did work for me (at least the site was back). Can't give you any more input 'cos I haven't used it yet. I'm also new to the Layout plugin, so I'm lost on any of their inner workings.

**Comment by arnoson** [comment]
In Kirby 3.9 it will be possible to use snippets with slots:
```php
<?php snippet('article', slots: true) ?>
  <?php slot('header') ?>
    <h1>This is the title</h1>
  <?php endslot() ?>

  <?php slot('body') ?>
    <p>This is some body text</p>
  <?php endslot() ?>
<?php endsnippet() ?>
```
which would make this plugin obsolete. I still like having components inside an extra folder and the explicit `beginComponent` and `endComponent` instead of `slots: true`. But maybe this isn't be worth it and going with the kirby 3.9 feature is the way to go.

**Comment by WebMechanic** [comment]
ok then. thanks. I have other interests than Kirby that keep me busy, so I don't follow their news closely. I just like the idea of having text files for contents and the templateing seems simple enough.

I was still evaluating both Layouts and this so there's not much work done here refactoring existing snippets for their "componentability".

I agree, that the component concept seems better suited as a mental model to some code that's now implemented as a snippet. That folder can get crowded, but maybe some name spacing will help.

**Comment by arnoson** [comment]
If you like Vue and a component structure where template, js and css are co-located you might be interested in this: I have created an [example setup](https://github.com/arnoson/kirby-petite-vue-kit) for using petite-vue components with kirby 3.9 snippets.

Together with VS Code file nesting settings I get a good structure, as if the files were in a folder:

![Screenshot_20230110_093244](https://user-images.githubusercontent.com/15122993/211501285-f45cf6d5-7194-4166-98af-4d59b7795e6a.png)

Components are just snippets with slots. Template php, js and css are also co-located.

So there is no `src` folder anymore that is separated from kirby, and everything is like a component.
Of course this setup doesn't rely on petite vue, could also be vanilla js/ts, alpine.js, ...

**Comment by WebMechanic** [comment]
nice, I was also toying with petite-vue :D
That's pretty much the same layout I have now (using PhpStorm for this project)

This site needs very little .js so there's no Node or JS-bundling shenanigans involved. A couple of files are simply concatenated and minified. Old school without any SPA or PWA nonsense 😁 
I use PhpStorm's own file watcher to run the global Sass binary to use some of their magic.

The few "snippet" .js involved are also miniscule and are simply inlined by the template. 
I also added .css to a handful unique-ish `content/` pages that need some extra love but where the CSS is just a couple of lines. That too gets inlined into the HTML.
